#!/bin/bash

#--------------------------------------------------------------
# Mail‑Server Auto‑Installer (Postfix + Dovecot + OpenDKIM)
# Hardened Edition – June 2025
#--------------------------------------------------------------
#
# • Sets up a single‑domain virtual‑mail Postfix/Dovecot stack
# • Adds modern best‑practice security knobs (TLS ≥ 1.2, HELO &
#   recipient checks, Fail2Ban, DKIM)
#
# ***  CUSTOMISE THE VARIABLES BELOW  ***
#--------------------------------------------------------------

DOMAIN="domain.de"               # Your primary mail domain
MAIL_USER="info"                 # First mailbox user (local‑part)
MAIL_PASS="PASSWORT"        # Initial password (will be hashed)
HOSTNAME="mail.$DOMAIN"          # FQDN of this host / MX / cert CN
VMAIL_UID=5000                    # UID/GID for virtual mailbox user
VMAIL_GID=5000
VMAIL_DIR="/var/mail/vhosts"     # Root dir for vmail structure

#--------------------------------------------------------------
# 0 )  Sanity checks
#--------------------------------------------------------------
[[ $EUID -ne 0 ]] && { echo "[FATAL] Run as root"; exit 1; }

#--------------------------------------------------------------
# 1 )  Basic system prep
#--------------------------------------------------------------

echo "[+] Setting hostname to $HOSTNAME" && hostnamectl set-hostname "$HOSTNAME"

echo "[+] Updating base system …" && apt update && apt upgrade -y

#--------------------------------------------------------------
# 2 )  Install required packages
#--------------------------------------------------------------

echo "[+] Installing packages …"
apt install -y postfix postfix-mysql dovecot-core dovecot-imapd dovecot-lmtpd \
               opendkim opendkim-tools \
               mailutils ufw fail2ban certbot

#--------------------------------------------------------------
# 3 )  Obtain Let’s‑Encrypt certificate (stand‑alone)
#--------------------------------------------------------------

echo "[+] Requesting Let’s Encrypt cert for $HOSTNAME …"
certbot certonly --standalone -d "$HOSTNAME" --non-interactive --agree-tos -m "admin@$DOMAIN"

if [[ ! -f "/etc/letsencrypt/live/$HOSTNAME/fullchain.pem" ]]; then
  echo "[FATAL] Certificate retrieval failed → check DNS / ports 80+443"; exit 1
fi

#--------------------------------------------------------------
# 4 )  Postfix configuration
#--------------------------------------------------------------

echo "[+] Configuring Postfix …"
cp /etc/postfix/main.cf "/etc/postfix/main.cf.$(date +%F).bak"
cp /etc/postfix/master.cf "/etc/postfix/master.cf.$(date +%F).bak"

cat >/etc/postfix/main.cf <<EOF
# -------------------------------------------------------------
#  Postfix main.cf – generated by install‑script
# -------------------------------------------------------------

# --- General --------------------------------------------------
smtpd_banner = \$myhostname ESMTP \$mail_name (Secure)
biff = no
append_dot_mydomain = no

myhostname = $HOSTNAME
myorigin   = /etc/mailname
mydestination = \$myhostname, localhost.\$mydomain, localhost
relayhost  =
inet_interfaces = all
inet_protocols = ipv4

# --- TLS / SSL -----------------------------------------------
smtpd_use_tls            = yes
smtpd_tls_cert_file      = /etc/letsencrypt/live/$HOSTNAME/fullchain.pem
smtpd_tls_key_file       = /etc/letsencrypt/live/$HOSTNAME/privkey.pem

#  Opportunistic TLS on MX (Port 25)
smtpd_tls_security_level = may
#  Harden protocol / ciphers (TLS ≥ 1.2)
smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1
smtpd_tls_mandatory_ciphers   = high
smtpd_tls_session_cache_database = btree:\${data_directory}/smtpd_scache
smtp_tls_session_cache_database  = btree:\${data_directory}/smtp_scache

# --- SMTP authentication (Submission 587) -----------------
smtpd_sasl_auth_enable       = yes
smtpd_sasl_type              = dovecot
smtpd_sasl_path              = private/auth
smtpd_sasl_security_options  = noanonymous
smtpd_tls_auth_only          = yes

# --- Post-screen ------------------------------------ 
postscreen_access_list     = permit_mynetworks
postscreen_greet_wait      = 8s
postscreen_greet_action    = enforce
postscreen_dnsbl_sites     = zen.spamhaus.org*3, b.barracudacentral.org*2
postscreen_dnsbl_threshold = 4
postscreen_dnsbl_action    = enforce

# --- HELO & client sanity checks ------------------------------
smtpd_helo_required    = yes
smtpd_helo_restrictions= reject_invalid_helo_hostname,reject_non_fqdn_helo_hostname,permit

# --- Recipient restrictions ----------------------------------
smtpd_recipient_restrictions = \
    permit_mynetworks, \
    permit_sasl_authenticated, \
    reject_non_fqdn_recipient, \
    reject_unknown_recipient_domain, \
    reject_unverified_recipient, \
    reject_unauth_destination

# --- Virtual mailbox setup -----------------------------------
virtual_mailbox_domains = $DOMAIN
virtual_mailbox_base    = $VMAIL_DIR
virtual_mailbox_maps    = hash:/etc/postfix/vmailbox
virtual_minimum_uid     = $VMAIL_UID
virtual_uid_maps        = static:$VMAIL_UID
virtual_gid_maps        = static:$VMAIL_GID
virtual_transport       = lmtp:unix:private/dovecot-lmtp

# --- DKIM Milter ---------------------------------------------
milter_default_action = accept
smtpd_milters   = inet:localhost:12301
non_smtpd_milters = inet:localhost:12301

EOF

#---  master.cf tweaks (Submission + Postscreen) --------------------


cat >/etc/postfix/master.cf <<'EOF'
# =====================  Eingehende MTA-Verbindung  (Port 25) =====================
smtp      inet  n  -  y  -  1  postscreen
smtpd     pass  -  -  y  -  -  smtpd
dnsblog   unix  -  -  y  -  0  dnsblog
tlsproxy  unix  -  -  y  -  0  tlsproxy

# =====================  Submission für Mail-Clients (Port 587) ==================
submission inet n  -  y  -  -  smtpd
  -o syslog_name=postfix/submission
  -o smtpd_sasl_auth_enable=yes              
  -o smtpd_reject_unlisted_recipient=no
  -o milter_macro_daemon_name=ORIGINATING    
  
# ----------------------------------------------------------------------
# Basisdienste – NICHT löschen!
pickup    unix  n       -       y       60      1       pickup
cleanup   unix  n       -       y       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
#qmgr     unix  n       -       n       300     1       oqmgr
tlsmgr    unix  -       -       y       1000?   1       tlsmgr
rewrite   unix  -       -       y       -       -       trivial-rewrite
bounce    unix  -       -       y       -       0       bounce
defer     unix  -       -       y       -       0       bounce
trace     unix  -       -       y       -       0       bounce
verify    unix  -       -       y       -       1       verify
flush     unix  n       -       y       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       y       -       -       smtp
relay     unix  -       -       y       -       -       smtp
        -o syslog_name=postfix/$service_name
#       -o smtp_helo_timeout=5 -o smtp_connect_timeout=5
showq     unix  n       -       y       -       -       showq
error     unix  -       -       y       -       -       error
retry     unix  -       -       y       -       -       error
discard   unix  -       -       y       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       y       -       -       lmtp
anvil     unix  -       -       y       -       1       anvil
scache    unix  -       -       y       -       1       scache
postlog   unix-dgram n  -       n       -       1       postlogd

EOF

systemctl restart postfix

#--------------------------------------------------------------
# 5 )  Dovecot configuration
#--------------------------------------------------------------

echo "[+] Configuring Dovecot …"
groupadd -g "$VMAIL_GID" vmail 2>/dev/null || true
useradd  -g vmail -u "$VMAIL_UID" vmail -d /var/mail 2>/dev/null || true

mkdir -p "$VMAIL_DIR/$DOMAIN/$MAIL_USER/Maildir"
chown -R vmail:vmail "$VMAIL_DIR"
chmod -R 700 "$VMAIL_DIR"

cat >/etc/dovecot/dovecot.conf <<EOF
# -------------------------------------------------------------
#  Dovecot v2.x config
# -------------------------------------------------------------
protocols = imap lmtp
mail_location = maildir:$VMAIL_DIR/%d/%n/Maildir

namespace inbox {
  inbox = yes
}

auth_mechanisms = plain login

passdb {
  driver = passwd-file
  args   = scheme=SHA512-CRYPT username_format=%u /etc/dovecot/users
}

userdb {
  driver = static
  args   = uid=$VMAIL_UID gid=$VMAIL_GID home=$VMAIL_DIR/%d/%n
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode  = 0660
    user  = postfix
    group = postfix
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode  = 0600
    user  = postfix
    group = postfix
  }
}

# --- SSL / TLS -----------------------------------------------
ssl = required
ssl_cert = </etc/letsencrypt/live/$HOSTNAME/fullchain.pem
ssl_key  = </etc/letsencrypt/live/$HOSTNAME/privkey.pem
#  Only TLS ≥ 1.2
ssl_min_protocol = TLSv1.2
ssl_cipher_list  = HIGH:!aNULL:!MD5
EOF

PASSWORD_HASH=$(doveadm pw -s SHA512-CRYPT -u "$MAIL_USER@$DOMAIN" -p "$MAIL_PASS")

echo "[+] Adding first mailbox user …"
echo "$MAIL_USER@$DOMAIN:$PASSWORD_HASH" > /etc/dovecot/users

systemctl restart dovecot

#--------------------------------------------------------------
# 6 )  Postfix virtual‑mailbox map
#--------------------------------------------------------------

echo "[+] Creating virtual mailbox map …"
echo "$MAIL_USER@$DOMAIN    $DOMAIN/$MAIL_USER/" > /etc/postfix/vmailbox
postmap /etc/postfix/vmailbox

#--------------------------------------------------------------
# 7 )  OpenDKIM
#--------------------------------------------------------------

echo "[+] Setting up OpenDKIM …"
mkdir -p /etc/opendkim/keys/$DOMAIN
chown -R opendkim:opendkim /etc/opendkim

opendkim-genkey -D /etc/opendkim/keys/$DOMAIN/ -d "$DOMAIN" -s mail
chown opendkim:opendkim /etc/opendkim/keys/$DOMAIN/mail.private
chmod 600 /etc/opendkim/keys/$DOMAIN/mail.private

cat >/etc/opendkim.conf <<EOF
Syslog                  yes
UMask                   002
Mode                    sv
Canonicalization        relaxed/simple
OversignHeaders         From
Domain                  $DOMAIN
KeyFile                 /etc/opendkim/keys/$DOMAIN/mail.private
Selector                mail
Socket                  inet:12301@localhost
PidFile                 /run/opendkim/opendkim.pid
UserID                  opendkim:opendkim
EOF

cat >/etc/opendkim/TrustedHosts <<EOF
127.0.0.1
localhost
$DOMAIN
EOF

cat >/etc/opendkim/KeyTable <<EOF
mail._domainkey.$DOMAIN $DOMAIN:mail:/etc/opendkim/keys/$DOMAIN/mail.private
EOF

cat >/etc/opendkim/SigningTable <<EOF
*@$DOMAIN mail._domainkey.$DOMAIN
EOF

mkdir -p /run/opendkim && chown opendkim:opendkim /run/opendkim && chmod 750 /run/opendkim

systemctl restart opendkim

# DKIM in Postfix already set in main.cf ↑

#--------------------------------------------------------------
# 8 )  Firewall (UFW)
#--------------------------------------------------------------

echo "[+] Configuring firewall …"
ufw default deny incoming
ufw default allow outgoing
for p in 22 25  587 993; do ufw allow ${p}/tcp; done
ufw --force enable

#--------------------------------------------------------------
# 9 )  Fail2Ban
#--------------------------------------------------------------

echo "[+] Configuring Fail2Ban …"
cat >/etc/fail2ban/jail.local <<'EOF'
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 5

[sshd]
enabled = true
port    = ssh
logpath = %(sshd_log)s
backend = %(sshd_backend)s

[postfix]
enabled = true
port    = smtp,submissions,465
logpath = journal
backend = systemd

[postfix-sasl]
enabled = true
port    = smtp,submissions,465
filter  = postfix-sasl
logpath = journal
backend = systemd

[dovecot]
enabled = true
port    = imap,imaps,pop3,pop3s
logpath = journal
backend = systemd
EOF

systemctl restart fail2ban

#--------------------------------------------------------------
# 10 )  DNS records helper
#--------------------------------------------------------------

echo "\n[!]  Add the following DNS records now:\n"

echo "-- DKIM (TXT) -------------------------------------------"
cat /etc/opendkim/keys/$DOMAIN/mail.txt

echo "\n-- SPF ------------------------------------------------------"
echo "@ IN TXT \"v=spf1 mx a -all\""

echo "\n-- DMARC ----------------------------------------------------"
echo "_dmarc IN TXT \"v=DMARC1; p=quarantine; rua=mailto:postmaster@$DOMAIN; aspf=r; adkim=r;\""

#  (Optional) MTA‑STS & TLS‑RPT instructions

cat <<'INFO'

-----------------------------------------------------------------
Optional but recommended:
• Publish an _smtp._tls TXT record for TLS‑RPT:
    _smtp._tls.$DOMAIN.  IN TXT  "v=TLSRPTv1; rua=mailto:tlsrpt@$DOMAIN"
• Deploy MTA‑STS policy and corresponding DNS record.
• Add DNSSEC + TLSA records (DANE) if your registrar supports it.
-----------------------------------------------------------------
INFO

echo "\n[OK] Installation complete!  You can now log in via IMAP (993) using $MAIL_USER@$DOMAIN"
